#!/usr/bin/env bash
# gen-policy-manifest.sh
#
# Generate POLICY_MANIFEST.md from the canonical source of truth: the
# `policy_module(name, X.Y.Z)` declaration in each .te file. The manifest
# is what release notes and downstream consumers cite when they say
# "policy bundle X has these modules at these versions" -- it must never
# drift from the .te files themselves.
#
# CI runs this in --check mode and fails if the committed manifest does
# not match what the .te files would produce right now. That ties the
# documentation to the policy in a way that cannot rot silently.
#
# Usage:
#   ./scripts/gen-policy-manifest.sh           # rewrite POLICY_MANIFEST.md
#   ./scripts/gen-policy-manifest.sh --check   # exit 1 if regeneration would change it

set -euo pipefail

MODE="${1:-write}"
REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "$REPO_ROOT"

POLICY_DIR="recipes-security/refpolicy/files"
OUT="POLICY_MANIFEST.md"
TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Build the manifest in a temp file first so --check can diff cleanly.
{
    cat <<'HEADER'
# Policy Module Manifest

Generated by `scripts/gen-policy-manifest.sh`. Do not edit by hand --
CI re-runs the generator in `--check` mode on every push and rejects
the change if this file is stale relative to the `.te` sources.

The version of each module is the second argument of its
`policy_module(name, X.Y.Z)` declaration. That declaration is the
canonical source of truth for module identity and version; the table
below is a derived view used by release notes, supply-chain audits,
and signed manifest consumers.

| Module | Version | `.te` source |
|---|---|---|
HEADER

    # Sort by module name (which equals filename without extension), so the
    # ordering is stable across machines and matches the layout of an
    # alphabetically-sorted directory listing.
    for te in "$POLICY_DIR"/*.te; do
        base="$(basename "$te" .te)"
        # Match: policy_module(<name>, <version>) on a single line, allow
        # whitespace inside the parens. The CI structure check already
        # asserts that each .te has exactly one such declaration in its
        # first 20 lines, so a single grep here is sufficient.
        decl="$(head -20 "$te" | grep -E '^policy_module\(' | head -1 || true)"
        if [[ -z "$decl" ]]; then
            echo "::error file=$te::no policy_module() declaration" >&2
            exit 1
        fi
        # Strip 'policy_module(' prefix and trailing ')' then split on comma.
        inner="${decl#policy_module(}"
        inner="${inner%)}"
        name="$(echo "$inner" | cut -d, -f1 | tr -d ' ')"
        version="$(echo "$inner" | cut -d, -f2 | tr -d ' ')"
        if [[ "$name" != "$base" ]]; then
            echo "::error file=$te::policy_module name '$name' does not match filename '$base'" >&2
            exit 1
        fi
        printf '| `%s` | `%s` | [`%s/%s.te`](%s/%s.te) |\n' \
            "$name" "$version" "$POLICY_DIR" "$base" "$POLICY_DIR" "$base"
    done | LC_ALL=C sort

    cat <<'FOOTER'

## Verification

To verify that this manifest matches the policy sources locally:

```sh
./scripts/gen-policy-manifest.sh --check
```

To regenerate after a `policy_module()` version bump:

```sh
./scripts/gen-policy-manifest.sh
git add POLICY_MANIFEST.md
```

A version bump in any `.te` MUST be accompanied by a regenerated manifest
in the same commit. CI enforces this.
FOOTER
} > "$TMP"

case "$MODE" in
    --check)
        if ! diff -u "$OUT" "$TMP"; then
            echo "::error::POLICY_MANIFEST.md is stale. Run scripts/gen-policy-manifest.sh and commit." >&2
            exit 1
        fi
        echo "POLICY_MANIFEST.md is up to date."
        ;;
    write|"")
        mv "$TMP" "$OUT"
        trap - EXIT
        echo "Wrote $OUT"
        ;;
    *)
        echo "usage: $0 [--check]" >&2
        exit 2
        ;;
esac
